# Konfigurasi Redirect untuk Link Pendek

[[redirects]]
  from = "/s/lapor"
  to = "https://vektor-rspr.netlify.app/"
  status = 302
  force = true

[[redirects]]
  from = "/s/status"
  to = "/?v=status"
  status = 302
  force = true

[[redirects]]
  from = "/s/admin"
  to = "/?v=admin"
  status = 302
  force = true

[[redirects]]
  from = "/s/home"
  to = "/"
  status = 302
  force = true

[[redirects]]
  from = "/s/track"
  to = "/?v=status"
  status = 302
  force = true

# Rewrite supaya aplikasi tidak error saat refresh
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
